# pre-commit 1.1.0 is required for `exclude`
# however `minimum_pre_commit_version` itself requires 1.15.0
minimum_pre_commit_version: 1.15.0

exclude: ^(yt/extern|yt/frontends/stream/sample_data|yt/units|scripts|benchmark|setupext.py|yt/visualization/_colormap_data.py)

ci:
  autofix_prs: false
  autoupdate_schedule: quarterly

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: no-commit-to-branch
  - id: debug-statements
  - id: check-merge-conflict
- repo: https://github.com/neutrinoceros/inifix.git
  rev: v4.0.0
  hooks:
  - id: inifix-format
- repo: https://github.com/asottile/pyupgrade
  rev: v3.3.1
  hooks:
  - id: pyupgrade
    args: [--py38-plus]
- repo: https://github.com/psf/black
  rev: 22.12.0
  hooks:
  - id: black
    language_version: python3
- repo: https://github.com/PyCQA/isort
  rev: 5.12.0
  hooks:
  - id: isort
    name: isort (python)
  - id: isort
    name: isort (cython)
    types: [cython]
- repo: https://github.com/PyCQA/flake8
  rev: 6.0.0
  hooks:
  - id: flake8
    additional_dependencies: [flake8-bugbear==22.7.1, flake8-logging-format==0.7.4, flake8-2020==1.6.0]

- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.6.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix, --indent, '2']
