ci:
  autofix_prs: false
  autoupdate_schedule: quarterly

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: no-commit-to-branch
  - id: debug-statements
  - id: check-merge-conflict

- repo: https://github.com/neutrinoceros/inifix.git
  rev: v4.0.0
  hooks:
  - id: inifix-format

- repo: https://github.com/psf/black
  rev: 22.12.0
  hooks:
  - id: black
    language_version: python3

- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: v0.0.237
  hooks:
  - id: ruff
    args: [--fix]

- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.6.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix, --indent, '2']
