name: CI (bleeding edge)
# this workflow is heavily inspired from pandas, see
# https://github.com/pandas-dev/pandas/blob/master/.github/workflows/python-dev.yml

# goals: check stability against dev version of Python and yt
# - building with future pip default options

on:
  push:
    branches:
    - main
  pull_request:
    paths:
    - .github/workflows/bleeding-edge.yaml
  schedule:
    # run this every Wednesday at 3 am UTC
  - cron: 0 3 * * 3
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: CI w/ yt dev
    timeout-minutes: 60

    concurrency:
      group: ${{ github.ref }}-dev
      cancel-in-progress: true

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Python Dev Version
      uses: actions/setup-python@v4
      with:
        python-version: 3.12-dev

    - name: Build
      run: |
        python -m pip install --upgrade pip
        python -m pip install --pre --extra-index \
          https://pypi.anaconda.org/scientific-python-nightly-wheels/simple numpy matplotlib
        python -m pip install git+https://github.com/yt-project/yt.git
        python -m pip install .
        python -m pip install --requirement requirements/tests.txt

    - run: python -m pip list

    - name: Run Tests
      run: pytest --color=yes
