name: CI

on:
  push:
    branches:
      - main
  pull_request:
    paths-ignore:
      - README.md
  schedule:
    # run this every day at 3 am UTC
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  tests:
    strategy:
      matrix:
        os: [
          ubuntu-latest,
        ]
        python-version: [
          '3.7',
          #'3.9',
        ]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true
    - name: Checkout LFS objects
      run: git lfs checkout
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Setup package
      run: python3 -m pip install -e .[dev]
    - name: run tests
      run: pytest
