name: CI

on:
  push:
    branches:
    - main
  pull_request:
    paths-ignore:
    - README.md
  schedule:
    # run this every Wednesday at 3 am UTC
  - cron: 0 3 * * 3
  workflow_dispatch:

jobs:
  tests:
    strategy:
      matrix:
        os:
        - ubuntu-latest
        python-version:
        - '3.10'
        - '3.13'
        install-args:
        - ''
        - --extra HDF5

        include:
        - os: ubuntu-20.04
          python-version: '3.10'
          install-args: --extra HDF5 --resolution=lowest-direct

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - uses: astral-sh/setup-uv@4db96194c378173c656ce18a155ffc14a9fc4355 # v5.2.2
      with:
        python-version: ${{ matrix.python-version }}

    - name: run tests
      run: |
        uv run --group test ${{ matrix.install-args }} \
          pytest --color=yes


  type-check:
    runs-on: ubuntu-latest
    name: type check

    strategy:
      matrix:
        python-version:
        - '3.10'
        - '3.13'

    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - uses: astral-sh/setup-uv@4db96194c378173c656ce18a155ffc14a9fc4355 # v5.2.2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Typecheck
      run: |
        uv run --frozen --group typecheck mypy src
