name: CI

on:
  push:
    branches:
      - main
  pull_request:
    paths-ignore:
      - README.md
  schedule:
    # run this every day at 3 am UTC
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  tests:
    strategy:
      matrix:
        os:
          - ubuntu-latest
        python-version:
          - '3.8'
          - '3.11'

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Build
      run: |
        python3 -m pip install -U pip
        python3 -m pip install ".[test]"
    - name: run tests
      run: pytest --color=yes


  type-check:
    runs-on: ubuntu-latest
    name: type check

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        # Match minimal supported Python version
        # to make sure we're not using unparseable syntax
        python-version: '3.8'

    - name: Build
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install .[typecheck]

    - name: Run mypy
      run: mypy yt_idefix
